name: Release on Merge to Master

on:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get version from README
      id: get_version
      run: |
        first_line=$(head -n 1 README.md)
        version=$(echo $first_line | grep -oP '(?<=—\s)v[0-9]+\.[0-9]+\.[0-9]+')
        if [ -z "$version" ]; then
          echo "Version non trouvée dans README.md"
          exit 1
        fi
        clean_version=$(echo $version | sed 's/^v//')
        echo "version=${clean_version}" >> $GITHUB_ENV

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version }}
        release_name: ${{ env.version }}
        draft: false
        prerelease: false